planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.0
  RRTstar:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1
arm:
  default_planner_config: RRTConnect
  planner_configs: [RRTConnect, RRTstar]
  projection_evaluator: joints(joint1,joint2)
  longest_valid_segment_fraction: 0.005
