#!/usr/bin/env python3
"""Write a VINS-Mono config for the simulated mast camera.

Intrinsics are taken from the camera_info Gazebo actually publishes rather than
recomputed from the xacro's horizontal_fov, and the camera-IMU extrinsic is read
out of TF rather than assembled by hand from the joint origins. Both are things
that silently go stale when the URDF is edited, and a wrong extrinsic in VINS
shows up as slow drift rather than as an error.
"""
import sys

import numpy as np
import rospy
import tf2_ros
import tf.transformations as tft
from sensor_msgs.msg import CameraInfo

OUT = sys.argv[1] if len(sys.argv) > 1 else "/tmp/vineyard_vins.yaml"
IMU_FRAME = "imu_link"
CAM_OPTICAL = "camera_depth_optical_frame"

rospy.init_node("make_vins_config", anonymous=True)

info = rospy.wait_for_message("/camera/color/camera_info", CameraInfo,
                              timeout=20)
fx, fy = info.K[0], info.K[4]
cx, cy = info.K[2], info.K[5]
w, h = info.width, info.height

buf = tf2_ros.Buffer()
tf2_ros.TransformListener(buf)
rospy.sleep(1.5)
t = buf.lookup_transform(IMU_FRAME, CAM_OPTICAL, rospy.Time(0),
                         rospy.Duration(10.0))
q = [t.transform.rotation.x, t.transform.rotation.y,
     t.transform.rotation.z, t.transform.rotation.w]
R = tft.quaternion_matrix(q)[0:3, 0:3]
p = [t.transform.translation.x, t.transform.translation.y,
     t.transform.translation.z]


def mat(rows):
    return "[" + ", ".join("%.8f" % v for r in rows for v in r) + "]"


yaml = """%%YAML:1.0
# VINS-Mono config for the greenhouse vineyard sim.
#
# Generated by scripts/make_vins_config.py against a running simulation: the
# intrinsics come from the camera_info Gazebo publishes and the extrinsic comes
# out of TF, so neither can drift away from the URDF by hand-editing.
#
# The camera is the forward-looking mast RGB-D, NOT the eye-in-hand RealSense.
# The mast one is rigidly attached to the chassis, which is what the extrinsic
# below assumes; the wrist camera moves relative to the IMU every time the arm
# does, and VINS has no way to know that.

imu_topic: "/imu/data"
image_topic: "/camera/color/image_raw"
output_path: "/catkin_ws/vins_output/"

model_type: PINHOLE
camera_name: mast
image_width: %d
image_height: %d
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: %.6f
   fy: %.6f
   cx: %.6f
   cy: %.6f

# 0 = the extrinsic is known and fixed. It is: both the camera and the IMU are
# bolted to the same chassis and the transform is read straight out of the URDF,
# so there is nothing for the estimator to discover.
estimate_extrinsic: 0
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: %s
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [%.8f, %.8f, %.8f]

# Feature tracking. The vineyard is a repetitive scene -- posts, wires and leaf
# tiles that all look alike -- so the tracker is given more features than the
# EuRoC default and a larger minimum spacing, to stop them all piling onto one
# trellis post.
max_cnt: 200
min_dist: 25
freq: 10
F_threshold: 1.0
show_track: 0
equalize: 1
fisheye: 0

# Gazebo's IMU plugin here is configured without noise, so these are nominal
# MEMS figures rather than measured ones: they have to be non-zero or the
# estimator trusts the IMU absolutely and refuses to correct it visually.
acc_n: 0.08
gyr_n: 0.004
acc_w: 0.00004
gyr_w: 0.000002
g_norm: 9.80665

loop_closure: 1
load_previous_pose_graph: 0
fast_relocalization: 0
pose_graph_save_path: "/catkin_ws/vins_output/pose_graph/"

# The platform crawls at 0.45 m/s and stops to cut, so there is no rolling
# shutter compensation to do and no time offset worth estimating.
estimate_td: 0
td: 0.0
rolling_shutter: 0
rolling_shutter_tr: 0.0

visualize_imu_forward: 0
visualize_camera_size: 0.4
""" % (w, h, fx, fy, cx, cy, mat(R), p[0], p[1], p[2])

with open(OUT, "w") as f:
    f.write(yaml)

print("wrote %s" % OUT)
print("  image      %dx%d" % (w, h))
print("  intrinsics fx=%.2f fy=%.2f cx=%.2f cy=%.2f" % (fx, fy, cx, cy))
print("  %s -> %s" % (IMU_FRAME, CAM_OPTICAL))
print("    translation [%.4f, %.4f, %.4f]" % (p[0], p[1], p[2]))
print("    rotation")
for r in R:
    print("      [%+.4f %+.4f %+.4f]" % tuple(r))
